Portfolio desktop version
nati2323/Final-Mobile-and-Desktop-Portfolio pull request #3
Opened 2022-05-05 08:44 UTC by nati2323

- Added Media Query in my CSS file.
- Added Grid and Flexbox to lay out the elements on the page.

2022-05-05 11:02 UTC, sja-thedude requested changes
## Required Changes ♻️

Hi @nati2323, This is @sja-thedude your code reviewer.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![768070f3-bc9a-4aba-b8bc-25793e00ea1e_text](https://user-images.githubusercontent.com/70269507/159483175-2f61461d-b352-4cb4-98f8-b173e05ab5ff.gif)

## Highlights
✔️ All linters passing
✔️ Good PR description and title
✔️ Correct Gitflow

## Required 
- [ ]  Kindly make sure to use both Flexbox and Grid in order to layout the elements on the page for the desktop version also. You have implemented flexbox and grid in the mobile version. Kindly implement it for the desktop version.
- [ ] Kindly update your readme file with a correct description of the project and with your details.
- [ ] _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-05 11:02 UTC, sja-thedude commented on index.html
>              </li>
Mobile version:

- [ ] Kindly add the background image for the section as per the Figma design shown.
- [ ] Kindly make sure to change "My Projects" to "LET'S CONNECT" as per the Figma design.

https://user-images.githubusercontent.com/70269507/166904386-1768cafc-d765-4d70-a5c4-c103d9224b19.mov

2022-05-05 11:02 UTC, sja-thedude commented on index.html
>              </li>
Mobile Version:
- [ ] Kindly add the background image for the contact section as per the Figma design.
- [ ] Kindly change the placeholder for the input name and email field as per the Figma design.
- [ ] Kindly follow the text colour for the placeholder message text.
- [ ] Kindly follow the font weight for the paragraph as per the Figma design. 

https://user-images.githubusercontent.com/70269507/166905256-89a9d8bf-8f83-4b85-acfa-f8773a92fc07.mov

2022-05-05 11:02 UTC, sja-thedude commented on index.html
>              </li>
Mobile version:

- [ ] Kindly follow the correct font weight for the paragraph as per the Figma design.

https://user-images.githubusercontent.com/70269507/166906375-5513de21-1401-4712-97e9-afb5c5ba307e.mov

2022-05-05 11:02 UTC, sja-thedude commented on index.html
>              </li>
Mobile version:

- [ ] Kindly use the same images as given in the Figma design for the mobile version.
- [ ] Kindly Follow the same font-weight for the paragraph as per the Figma design.

https://user-images.githubusercontent.com/70269507/166907037-129dc94a-960e-4a11-b9f6-769502077101.mov

- [ ] Kindly follow the same text as per the given Figma design as given in the video below.
- [ ] Kindly follow the colours and background colour for lists as shown below.

https://user-images.githubusercontent.com/70269507/166908082-7799a246-1f2b-440b-8d76-3824630861ee.mov

2022-05-05 11:02 UTC, sja-thedude commented on index.html
>              </li>
Desktop Version:

- [ ] Kindly make sure you are following the Figma design for lists and displaying as shown for all the cards. 

https://user-images.githubusercontent.com/70269507/166908817-6cac64f0-0139-42d6-a464-fcaba0fe52d7.mov

2022-05-05 11:02 UTC, sja-thedude commented on index.html
> +               <input type="email" id="email" class="contact__email fw-500 fz-17 lh-20" placeholder="Enter your email"
Mobile version:

- [ ] Kindly follow the width for the input fields and the message field as per the Figma design. Also make sure, it is not round at the edges.

- Figma design:

<img width="718" alt="Screenshot 2022-05-05 at 1 53 08 PM" src="https://user-images.githubusercontent.com/70269507/166909383-75c40b5a-3a19-480f-a1ec-5e596c889974.png">

- Your design:

<img width="1106" alt="Screenshot 2022-05-05 at 1 53 26 PM" src="https://user-images.githubusercontent.com/70269507/166909386-4f9dd819-285a-4215-aa5c-9667af59a2d0.png">

2022-05-05 13:36 UTC, danmainah requested changes
Hi @nati2323 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has one of the linter checks failing kindly fix it.
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-05-05 14:15 UTC, danmainah commented on index.html
>              </li>
- [ ] Kindly implement the changes requested by the reviewer on the form, your form doesn't have background images as is in the design.

2022-05-05 14:15 UTC, danmainah commented on index.html
>              </li>
- [ ] Kindly implement the changes requested by the reviewer, the reviewer has a video showing the comparison of your design and the Figma design given.

2022-05-05 14:17 UTC, danmainah commented on index.html
>              </li>
- [ ] Kindly implement the changes requested by the reviewer, the reviewer has a video showing the comparison of your design and the Figma design given.

2022-05-05 14:17 UTC, danmainah commented on index.html
>              </li>
- [ ] Kindly implement the changes requested by the reviewer, the reviewer has a video showing the comparison of your design and the Figma design given.

2022-05-05 14:20 UTC, danmainah requested changes
Hi @nati2323, 

Great work on making the changes requested by a previous reviewer 👏  👏 👏
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
✔️ No linter errors
✔️ Github flow was correctly used


 # Required Changes ♻️

- [ ] Kindly implement the changes requested by the reviewer, the reviewer has videos showing the comparison of your design and the Figma design given in different sections where you made an error.

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-05 14:20 UTC, nati2323 commented
- Sorry for the Linters error now I have fixed all of them.

2022-05-07 10:37 UTC, prolajumokeoni approved these changes
Hi @nati2323, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- No linter errors ✅ 
- Github flow was used correctly 🚀 
- Good design 💯 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-08 13:09 UTC, merged

2022-05-08 14:37 UTC, nati2323 commented
***@***.***

On Sat, May 7, 2022 at 1:38 PM Oni Olajumoke Priscilla <
***@***.***> wrote:

> ***@***.**** approved this pull request.
>
> Hi @nati2323 <https://github.com/nati2323>,
>
> Your project is complete! There is nothing else to say other than... it's
> time to merge it [image: :shipit:]
> Congratulations! 🎉
> Highlights
>
>    - No linter errors ✅
>    - Github flow was used correctly 🚀
>    - Good design 💯
>
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> You can also consider:
>
>    - N/A
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification @prolajumokeoni <https://github.com/prolajumokeoni>.
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/nati2323/Mobile-Portfolio-1/pull/3#pullrequestreview-965319171>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXY4DOWSK4OMVIAOFBGNWTDVIZBYRANCNFSM5VELEU6Q>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-05-08 14:38 UTC, nati2323 commented
***@***.***,

On Sun, May 8, 2022 at 5:37 PM Natnael Amare ***@***.***> wrote:

> ***@***.***
>
> On Sat, May 7, 2022 at 1:38 PM Oni Olajumoke Priscilla <
> ***@***.***> wrote:
>
>> ***@***.**** approved this pull request.
>>
>> Hi @nati2323 <https://github.com/nati2323>,
>>
>> Your project is complete! There is nothing else to say other than... it's
>> time to merge it [image: :shipit:]
>> Congratulations! 🎉
>> Highlights
>>
>>    - No linter errors ✅
>>    - Github flow was used correctly 🚀
>>    - Good design 💯
>>
>> Optional suggestions
>>
>> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
>> the approval of this PR. However, I strongly recommend you to take them
>> into account as they can make your code better.*
>>
>> You can also consider:
>>
>>    - N/A
>>
>> Cheers and Happy coding!👏👏👏
>>
>> Feel free to leave any questions or comments in the PR thread if
>> something is not 100% clear.
>> Please, remember to tag me in your question so I can receive the
>> notification @prolajumokeoni <https://github.com/prolajumokeoni>.
>> ------------------------------
>>
>> *As described in the Code reviews limits policy
>> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
>> limited number of reviews per project (check the exact number in your
>> Dashboard). If you think that the code review was not fair, you can request
>> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/nati2323/Mobile-Portfolio-1/pull/3#pullrequestreview-965319171>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AXY4DOWSK4OMVIAOFBGNWTDVIZBYRANCNFSM5VELEU6Q>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> ***@***.***>
>>
>

2022-05-08 14:39 UTC, nati2323 commented
***@***.***

On Thu, May 5, 2022 at 2:02 PM Syeda Juveria Afreen <
***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> Required Changes ♻️
>
> Hi @nati2323 <https://github.com/nati2323>, This is @sja-thedude
> <https://github.com/sja-thedude> your code reviewer.
>
> Good job so far!
> There are some issues that you still need to work on to go to the next
> project but you are almost there!
>
> [image: 768070f3-bc9a-4aba-b8bc-25793e00ea1e_text]
> <https://user-images.githubusercontent.com/70269507/159483175-2f61461d-b352-4cb4-98f8-b173e05ab5ff.gif>
> Highlights
>
> ✔️ All linters passing
> ✔️ Good PR description and title
> ✔️ Correct Gitflow
> Required
>
>    - Kindly make sure to use both Flexbox and Grid in order to layout the
>    elements on the page for the desktop version also. You have implemented
>    flexbox and grid in the mobile version. Kindly implement it for the desktop
>    version.
>    - Kindly update your readme file with a correct description of the
>    project and with your details.
>    - *Check the comments under the review.*
>
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me ***@***.*** <https://github.com/sja-thedude>]
> in your question so I can receive the notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In index.html
> <https://github.com/nati2323/Mobile-Portfolio-1/pull/3#discussion_r865759709>
> :
>
> >                  name="contact_email" required/>
>
>              </li>
>
>              <li>
>
> -              <label for="message" class="fw-500 fz-17 lh-20">Message:</label>
>
>                <textarea id="message" class="fw-500 fz-17 lh-20" name="contact_message" placeholder="Write your message here"
>
>                  cols="30" rows="8" maxlength="500" required></textarea>
>
>              </li>
>
>
> Mobile version:
>
>    - Kindly add the background image for the section as per the Figma
>    design shown.
>    - Kindly make sure to change "My Projects" to "LET'S CONNECT" as per
>    the Figma design.
>
>
> https://user-images.githubusercontent.com/70269507/166904386-1768cafc-d765-4d70-a5c4-c103d9224b19.mov
> ------------------------------
>
> In index.html
> <https://github.com/nati2323/Mobile-Portfolio-1/pull/3#discussion_r865766015>
> :
>
> >                  name="contact_email" required/>
>
>              </li>
>
>              <li>
>
> -              <label for="message" class="fw-500 fz-17 lh-20">Message:</label>
>
>                <textarea id="message" class="fw-500 fz-17 lh-20" name="contact_message" placeholder="Write your message here"
>
>                  cols="30" rows="8" maxlength="500" required></textarea>
>
>              </li>
>
>
> Mobile Version:
>
>    - Kindly add the background image for the contact section as per the
>    Figma design.
>    - Kindly change the placeholder for the input name and email field as
>    per the Figma design.
>    - Kindly follow the text colour for the placeholder message text.
>    - Kindly follow the font weight for the paragraph as per the Figma
>    design.
>
>
> https://user-images.githubusercontent.com/70269507/166905256-89a9d8bf-8f83-4b85-acfa-f8773a92fc07.mov
> ------------------------------
>
> In index.html
> <https://github.com/nati2323/Mobile-Portfolio-1/pull/3#discussion_r865767835>
> :
>
> >                  name="contact_email" required/>
>
>              </li>
>
>              <li>
>
> -              <label for="message" class="fw-500 fz-17 lh-20">Message:</label>
>
>                <textarea id="message" class="fw-500 fz-17 lh-20" name="contact_message" placeholder="Write your message here"
>
>                  cols="30" rows="8" maxlength="500" required></textarea>
>
>              </li>
>
>
> Mobile version:
>
>    - Kindly follow the correct font weight for the paragraph as per the
>    Figma design.
>
>
> https://user-images.githubusercontent.com/70269507/166906375-5513de21-1401-4712-97e9-afb5c5ba307e.mov
> ------------------------------
>
> In index.html
> <https://github.com/nati2323/Mobile-Portfolio-1/pull/3#discussion_r865773194>
> :
>
> >                  name="contact_email" required/>
>
>              </li>
>
>              <li>
>
> -              <label for="message" class="fw-500 fz-17 lh-20">Message:</label>
>
>                <textarea id="message" class="fw-500 fz-17 lh-20" name="contact_message" placeholder="Write your message here"
>
>                  cols="30" rows="8" maxlength="500" required></textarea>
>
>              </li>
>
>
> Mobile version:
>
>    - Kindly use the same images as given in the Figma design for the
>    mobile version.
>    - Kindly Follow the same font-weight for the paragraph as per the
>    Figma design.
>
>
> https://user-images.githubusercontent.com/70269507/166907037-129dc94a-960e-4a11-b9f6-769502077101.mov
>
>    - Kindly follow the same text as per the given Figma design as given
>    in the video below.
>    - Kindly follow the colours and background colour for lists as shown
>    below.
>
>
> https://user-images.githubusercontent.com/70269507/166908082-7799a246-1f2b-440b-8d76-3824630861ee.mov
> ------------------------------
>
> In index.html
> <https://github.com/nati2323/Mobile-Portfolio-1/pull/3#discussion_r865779559>
> :
>
> >                  name="contact_email" required/>
>
>              </li>
>
>              <li>
>
> -              <label for="message" class="fw-500 fz-17 lh-20">Message:</label>
>
>                <textarea id="message" class="fw-500 fz-17 lh-20" name="contact_message" placeholder="Write your message here"
>
>                  cols="30" rows="8" maxlength="500" required></textarea>
>
>              </li>
>
>
> Desktop Version:
>
>    - Kindly make sure you are following the Figma design for lists and
>    displaying as shown for all the cards.
>
>
> https://user-images.githubusercontent.com/70269507/166908817-6cac64f0-0139-42d6-a464-fcaba0fe52d7.mov
> ------------------------------
>
> In index.html
> <https://github.com/nati2323/Mobile-Portfolio-1/pull/3#discussion_r865783521>
> :
>
> >                <input type="text" id="fname" class="contact__name fw-500 fz-17 lh-20" name="contact_name"
>
>                  placeholder="Enter your name" required maxlength="30" />
>
>              </li>
>
>              <li>
>
> -              <label for="email" class="fw-500 fz-17 lh-20">Email:</label>
>
> -              <input type="email" id="email" class="contact__email fw-500 fz-17 lh-20" placeholder="Enter your email"
>
> +               <input type="email" id="email" class="contact__email fw-500 fz-17 lh-20" placeholder="Enter your email"
>
>
> Mobile version:
>
>    -
>
>    Kindly follow the width for the input fields and the message field as
>    per the Figma design. Also make sure, it is not round at the edges.
>    -
>
>    Figma design:
>
> [image: Screenshot 2022-05-05 at 1 53 08 PM]
> <https://user-images.githubusercontent.com/70269507/166909383-75c40b5a-3a19-480f-a1ec-5e596c889974.png>
>
>    - Your design:
>
> [image: Screenshot 2022-05-05 at 1 53 26 PM]
> <https://user-images.githubusercontent.com/70269507/166909386-4f9dd819-28 [...]